export const EMAIL_VERIFICATION = 'EMAIL_VERIFICATION';
export const PASSWORD_RESET = 'PASSWORD_RESET';
export const GET_SAVED_BLOGS = 'GET_CLAPPED_BLOGS';
export const SAVE_BLOG = 'SAVE_BLOG';
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';
