# Generated by Django 3.1.2 on 2020-10-12 21:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20201012_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='clapped_blogs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Clapped Blogs'), blank=True, default=list, size=None),
        ),
    ]
