# Generated by Django 3.1.3 on 2020-11-15 17:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20201012_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='clapped_blogs',
        ),
        migrations.AddField(
            model_name='user',
            name='saved_blogs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Saved Blogs'), blank=True, default=list, size=None),
        ),
    ]
