version: '3.8'

services:

  macrobros-proxy:
    container_name: nginx_proxy
    restart: always
    build:
      context: nginx
    ports:
      - 80:80
    volumes:
      - "${EB_LOG_BASE_DIR}/macrobros-proxy:/var/log/nginx"
    depends_on:
      - macrobros-client

  macrobros-api:
    container_name: api
    restart: always
    build:
      context: backend
    env_file:
      - backend/environment/.env

  macrobros-client:
    container_name: client
    restart: always
    build:
      context: frontend
    depends_on:
      - macrobros-api
