version: '3.8'

services:

  macrobros-proxy:
    container_name: nginx_proxy
    restart: on-failure
    build:
      context: nginx
    ports:
      - "80:80"
    depends_on:
      - macrobros-client

  macrobros-api:
    container_name: api
    restart: on-failure
    build:
      context: backend
    ports:
      - "8000:8000"
    env_file:
      - backend/environment/.env

  macrobros-client:
    container_name: client
    restart: on-failure
    build:
      context: frontend
    depends_on:
      - macrobros-api
