version: '3.7'

services:
  proxy:
    build:
      context: ./nginx
    volumes:
      - static_data:/vol/static
    ports:
      - "8080:8080"
    depends_on:
      - macrobros_app

  macrobros_app:
    image: macrobros/macrobros-app
    container_name: macrobros_app
    volumes:
      - static_data:/vol/web
    env_file:
      - environment/.env

volumes:
  static_data: