export const ACCOUNT = {
	EMAIL_VERIFICATION: 'EMAIL_VERIFICATION',
	PASSWORD_RESET: 'PASSWORD_RESET',
	GET_SAVED_BLOGS: 'GET_CLAPPED_BLOGS',
	SAVE_BLOG: 'SAVE_BLOG',
	UPDATE_ACCOUNT: 'UPDATE_ACCOUNT'
};

export const AUTH = {
	USER_LOADING: 'USER_LOADING',
	USER_LOADED: 'USER_LOADED',
	AUTH_ERROR: 'AUTH_ERROR',
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_FAIL: 'LOGIN_FAIL',
	LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
	REGISTER_FAIL: 'REGISTER_FAIL',
	REGISTER_SUCCESS: 'REGISTER_SUCCESS',
	CLOSE_ACCOUNT: 'CLOSE_ACCOUNT'
};

export const BLOG = {
	GET_BLOG: 'RETRIEVE_BLOG_DETAILS',
	CLAP_BLOG: 'CLAP_BLOG',
	GET_BLOGS: 'RETRIEVING_ALL_BLOGS',
	GET_CATEGORY_BLOGS: 'RETRIEVING_CATEGORY_BLOGS',
	GET_BLOG_CATEGORIES: 'RETRIEVING_BLOG_CATEGORIES',
	GET_FEATURED_BLOG: 'RETRIEVING_FEATURED_BLOG',
	GET_POPULAR_BLOGS: 'RETRIEVING_POPULAR_BLOGS',
	SEARCH_BLOGS: 'SEARCHING_BLOGS'
};

export const CONTACT = {
	EMAIL_SENT: 'EMAIL_SENT'
};
