# Generated by Django 3.1.1 on 2020-09-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200906_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(verbose_name='Excerpt'),
        ),
    ]
