# Generated by Django 3.1.1 on 2020-09-07 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200906_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('Crypto', 'Crypto'), ('Finance', 'Finance'), ('Economics', 'Economics'), ('Macro', 'Macro'), ('Micro', 'Micro'), ('Tech', 'Tech'), ('Trading', 'Trading'), ('Investment', 'Investment')], default='Crypto', max_length=50, verbose_name='Category'),
        ),
    ]
