# Generated by Django 3.1.1 on 2020-09-07 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200907_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('crypto', 'Crypto'), ('finance', 'Finance'), ('economics', 'Economics'), ('macro', 'Macro'), ('micro', 'Micro'), ('tech', 'Tech'), ('trading', 'Trading'), ('investment', 'Investment')], default='crypto', max_length=50, verbose_name='Category'),
        ),
    ]
