# Generated by Django 3.1.1 on 2020-09-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200907_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='project_name',
            field=models.CharField(default='', max_length=100, verbose_name='Project Name'),
            preserve_default=False,
        ),
    ]
