# Generated by Django 3.1.1 on 2020-09-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogpost_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='ticker',
            field=models.CharField(default='', max_length=50, verbose_name='Ticker'),
            preserve_default=False,
        ),
    ]
