# Generated by Django 3.1.1 on 2020-09-14 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200911_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='thumbnail_alt',
            field=models.TextField(default='image txt', verbose_name='Tumbnail Alt'),
            preserve_default=False,
        ),
    ]
