# Generated by Django 3.1.1 on 2020-09-16 22:14

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blogpost_thumbnail_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='header_img',
            field=models.ImageField(blank=True, upload_to=blog.models.upload_to, verbose_name='Thumbnail'),
        ),
    ]
