# Generated by Django 3.1.1 on 2020-09-17 17:30

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blogpost_header_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='header_img',
            field=models.ImageField(blank=True, upload_to=blog.models.upload_to, verbose_name='Header Img'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ImageField(upload_to=blog.models.upload_to, verbose_name='Thumbnail Img'),
        ),
    ]
