# Generated by Django 3.1.1 on 2020-09-18 23:01

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200917_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ImageField(default='media/default/default-thumbnail.png', upload_to=blog.models.upload_to, verbose_name='Thumbnail Img'),
        ),
    ]
