# Generated by Django 3.1.1 on 2020-09-18 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200918_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='ticker',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ticker'),
        ),
    ]
