# Generated by Django 3.1.1 on 2020-09-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200920_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='popular',
            field=models.BooleanField(default=False, verbose_name='Popular'),
        ),
    ]
