# Generated by Django 3.1.1 on 2020-10-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_blogpost_popular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('crypto-projects', 'Crypto Projects'), ('macroeconomics', 'Macroeconomics'), ('company-analysis', 'Company Analysis')], default='crypto-projects', max_length=50, verbose_name='Category'),
        ),
    ]
