# Generated by Django 3.1.1 on 2020-10-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20201007_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='summary',
            field=models.TextField(default='', verbose_name='Summary'),
            preserve_default=False,
        ),
    ]
