# Generated by Django 3.1.1 on 2020-10-07 19:57

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_blogpost_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='icon',
            field=models.ImageField(default='/default/default-thumbnail.jpg', upload_to=blog.models.upload_to, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ImageField(default='/default/<django.db.models.fields.CharField>.jpg', upload_to=blog.models.upload_to, verbose_name='Thumbnail Img'),
        ),
    ]
