# Generated by Django 3.1.1 on 2020-10-07 20:07

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20201007_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='icon',
            field=models.ImageField(default='/default/category_icons/<django.db.models.fields.CharField>.svg', upload_to=blog.models.upload_to, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ImageField(default='/default/blog/default-thumbnail.jpg', upload_to=blog.models.upload_to, verbose_name='Thumbnail Img'),
        ),
    ]
