# Generated by Django 3.1.1 on 2020-10-07 20:13

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20201007_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='icon',
            field=models.FileField(default='/default/category_icons/<django.db.models.fields.CharField>.svg', upload_to=blog.models.upload_to, verbose_name='Icon'),
        ),
    ]
