# Generated by Django 3.1.2 on 2020-10-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_blogpost_read_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='read_time',
            field=models.CharField(blank=True, max_length=200, verbose_name='Read Time'),
        ),
    ]
