# Generated by Django 3.1.2 on 2020-10-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20201007_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='claps',
            field=models.IntegerField(blank=True, null=True, verbose_name='Claps'),
        ),
    ]
