# Generated by Django 3.1.2 on 2020-10-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_blogpost_claps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='claps',
            field=models.IntegerField(blank=True, default=0, verbose_name='Claps'),
        ),
    ]
