# Generated by Django 3.1.4 on 2020-12-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20201012_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnail_alt',
            field=models.TextField(verbose_name='Thumbnail Alt'),
        ),
    ]
