# Generated by Django 3.1.4 on 2020-12-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20201208_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='display_chart',
            field=models.BooleanField(default=False, verbose_name='Display Chart'),
        ),
    ]
