# Generated by Django 3.0.5 on 2020-09-02 20:39

import courses.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('price', courses.models.CurrencyField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('level', models.CharField(max_length=100, verbose_name='Level')),
                ('type', models.CharField(max_length=100, verbose_name='Type')),
                ('image', models.CharField(max_length=150, verbose_name='Image')),
                ('author', models.CharField(max_length=100, verbose_name='Author')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
            ],
        ),
    ]
