# Generated by Django 3.0.5 on 2020-09-02 20:48

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=djongo.models.fields.JSONField(default={}, verbose_name='Description'),
            preserve_default=False,
        ),
    ]
