export const GET_BLOG = 'RETRIEVE_BLOG_DETAILS';
export const GET_BLOGS = 'RETRIEVING_ALL_BLOGS';
export const GET_CATEGORY_BLOGS = 'RETRIEVING_CATEGORY_BLOGS';
export const GET_FEATURED_BLOG = 'RETRIEVING_FEATURED_BLOG';
