export const GET_BLOG = 'RETRIEVE_BLOG_DETAILS';
export const CLAP_BLOG = 'CLAP_BLOG';
export const GET_BLOGS = 'RETRIEVING_ALL_BLOGS';
export const GET_CATEGORY_BLOGS = 'RETRIEVING_CATEGORY_BLOGS';
export const GET_BLOG_CATEGORIES = 'RETRIEVING_BLOG_CATEGORIES';
export const GET_FEATURED_BLOG = 'RETRIEVING_FEATURED_BLOG';
export const GET_POPULAR_BLOGS = 'RETRIEVING_POPULAR_BLOGS';
export const SEARCH_BLOGS = 'SEARCHING_BLOGS';
