# Generated by Django 3.1.1 on 2020-09-24 20:52

import datetime
from django.db import migrations, models
import video.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('category', models.CharField(choices=[('crypto', 'Crypto'), ('macro', 'Macro'), ('precious-metals', 'Precious Metals'), ('wealth-cycles', 'Wealth Cycles')], default='crypto', max_length=50, verbose_name='Category')),
                ('header_img', models.ImageField(blank=True, upload_to=video.models.upload_to, verbose_name='Header Img')),
                ('thumbnail', models.ImageField(default='/default/default-thumbnail.jpg', upload_to=video.models.upload_to, verbose_name='Thumbnail Img')),
                ('thumbnail_alt', models.TextField(verbose_name='Tumbnail Alt')),
                ('excerpt', models.TextField(verbose_name='Excerpt')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Date Created')),
            ],
        ),
    ]
