# Generated by Django 3.1.1 on 2020-09-16 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terms_conditions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TermsAndConditions',
            new_name='TermsConditions',
        ),
    ]
