# Generated by Django 3.1.1 on 2020-09-16 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terms_conditions', '0003_termsconditions_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termsconditions',
            name='slug',
        ),
    ]
