# Generated by Django 3.1.1 on 2020-09-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms_conditions', '0004_remove_termsconditions_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsconditions',
            name='slug',
            field=models.CharField(default='', max_length=50, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
