# Generated by Django 3.1.1 on 2020-09-16 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms_conditions', '0005_termsconditions_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsconditions',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Date Created'),
        ),
    ]
